[package]
name = "chat_app_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
log = "0.4.22"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-tungstenite = "0.23.1"
env_logger = "0.11.3"
